# Локальная сеть
NETWORK = '10.10.20.'
# Имя для группы серверов
DOMAIN = '.otus.ru'
# Префикс для HDD
HDDLAST = '_hdd.vdi'
 
SERVERS =
[
	{
		:BOX_NAME => 'centos/7',
		:HOSTNAME => 'hw2' + DOMAIN,
		:IP => NETWORK + '1',
		:RAM => 2048,
		:CPU => '2',
		:HDDALL =>
		{
			:HDD1 =>
			{
			:HDDNAME => 'hw2_1' + HDDLAST,
			:HDD_SIZE => 256,
			:PORT => 1
			},
			:HDD2 =>
			{
			:HDDNAME => 'hw2_2' + HDDLAST,
			:HDD_SIZE => 256,
			:PORT => 2
			},
			:HDD3 =>
			{
			:HDDNAME => 'hw2_3' + HDDLAST,
			:HDD_SIZE => 256,
			:PORT => 3
			},
			:HDD4 =>
			{
			:HDDNAME => 'hw2_4' + HDDLAST,
			:HDD_SIZE => 256,
			:PORT => 4
			}
		}
	}
]

# Входим в Главную конфигурацию Vagrant версии 2
Vagrant.configure('2') do |config|
 
	# Проходим по элементах массива SERVERS
	SERVERS.each do |machine|
 
		# Применяем конфигурации для каждой машины
		config.vm.define machine[:HOSTNAME] do |node|
 
			# Создаем \ проверям box (Centos 7)
			node.vm.box = machine[:BOX_NAME]
 
			# Hostname который будет присвоен VM (самой ОС)
			node.vm.hostname = machine[:HOSTNAME]
 
			# Добавление и настройка внутреннего сетевого адаптера
			node.vm.network 'private_network', ip: machine[:IP]
 
			# Тонкие настройки (VirtualBox)
			node.vm.provider :virtualbox do |vb|
 
				# Размер RAM памяти
				vb.customize ['modifyvm', :id, '--memory', machine[:RAM]]
				# Количество CPU
				vb.customize ['modifyvm', :id, '--cpus', machine[:CPU]]
 
				# Перезапись названия VM в Vbox GUI
				vb.name = machine[:HOSTNAME]
 
				# Без этой опции была ошибка 0x80bb0004, так и не понял для чего она нужна конкретно
				needsController = false

				#Счетчик для новых HDD
				hddnew = 0

				# Проверка всех HDD (HDDALL)
				machine[:HDDALL].each do |hddcurrent, hddconfig|

					# Если диска не существует, создать
			  		unless File.exist?(hddconfig[:HDDNAME])
						vb.customize ['createhd', 
						'--filename', hddconfig[:HDDNAME],
						'--variant', 'Fixed',
						'--size', hddconfig[:HDD_SIZE]]
                                	hddnew = hddnew + 1
					end
				end
				
				if hddnew >= 1
					needsController =  true
				end

				# Если диск был создан, подключаем
				if needsController == true
					vb.customize ["storagectl", :id,
					"--name", "SATA",
					"--add", "SATA"]

                     			machine[:HDDALL].each do |hddcurrent, hddconfig|
						vb.customize ['storageattach', :id,
						'--storagectl', 'SATA',
						'--port', hddconfig[:PORT],
						'--device', 0,
						'--type', 'hdd',
						'--medium', hddconfig[:HDDNAME]]
					end
				end
			end
 
			# Настройки SSH
			node.vm.provision :shell do |s|
				s.inline = 'mkdir -p ~root/.ssh'
				s.inline = 'cp ~vagrant/.ssh/auth* ~root/.ssh'
			end
		end
	end
end
